### ISSUE TITLE
Additional commits on merged branches

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/lib-cove-oc4ids#10]
@michaelwood I see that there are two merged branches, with additional unmerged commits. Can you delete the branches, or create new issues/PRs if the new commits ought to be merged?

**Comment by jpmckinney** [comment]
Pinging @michaelwood

**Comment by michaelwood** [comment]
Same as https://github.com/open-contracting/lib-cove-oc4ids/issues/10 . Have deleted those branches now. Thanks.
